### ISSUE TITLE
Create a new front-end route

### ISSUE THREAD

**Issue by pedrowindisch** [itspenpals/penpals#15]
We need a new route that will handle the Letter view.

All letters will have a unique id that will be provided by the database, and the user can access a letter using its id, so I think it's a good idea to simply use a route with a parameter to the new view.

You can check how to use URL with parameters with React Router [here](https://reacttraining.com/react-router/web/example/url-params) 

All routes are being handled by [this file](https://github.com/itspenpals/penpals/blob/master/src/client/views/routes.jsx) .

**Comment by k1tsu** [comment]
#27
