### ISSUE TITLE
Mobile navbar

### ISSUE THREAD

**Issue by pedrowindisch** [itspenpals/penpals#22]
As our sidebar is almost ready (thanks @k1tsu!), I think we can start building its mobile version. @aditianshu did some wireframes to us showing how the navbar will look, and I found them really nice. 

Our app has a package that detects if the user is on a mobile device (check it docs [here](https://www.npmjs.com/package/react-device-detect), so I think it'd be interesting to make two separate components rather than using some tricky CSS hacks.

Our grid layout is _not yet_ optimized for mobile devices. You'll have to edit it to make it responsive - or render different grids based on the user device.

**Comment by k1tsu** [comment]
#25 Implemented the mobile Navbar:
<img width="1197" alt="Screen Shot 2020-04-08 at 3 38 52 PM" src="https://user-images.githubusercontent.com/45673607/78791160-cdf75e80-79af-11ea-9e20-a2ec6cb790fa.png">


However I did not make any changes to the Grid, it didn't give me any trouble.
