### ISSUE TITLE
Sidebar buttons actions

### ISSUE THREAD

**Issue by pedrowindisch** [itspenpals/penpals#29]
I added the dark mode support on the PR #28, but currently, there's no specific way to turn it on. For testing purposes, I added an onClick props on all sidebar buttons that will turn the dark mode on, but we need to change that so only the right button will switch the theme. 

The solution needs to be flexible, as all buttons will have an action. Maybe something like the snippet below works, but I didn't test it.

![carbon](https://user-images.githubusercontent.com/30203228/78897977-6988dd80-7a49-11ea-8643-23df0ac6a191.png)

**Comment by k1tsu** [comment]
#32
